const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
const ids = new Set([...html.matchAll(/\bid=["']([^"']+)["']/g)].map((match) => match[1]));
const selectors = [...app.matchAll(/\$\(\s*["'`]([^"'`]+)["'`]\s*\)/g)].map((match) => match[1]);
const referencedIds = new Set(selectors.flatMap((selector) => (
  [...selector.matchAll(/#([A-Za-z][\w-]*)/g)].map((match) => match[1])
)));
const missingIds = [...referencedIds].filter((id) => !ids.has(id)).sort();

assert.deepEqual(missingIds, [], `app.js references missing HTML ids: ${missingIds.join(", ")}`);

const motionIndex = html.indexOf("./motion-core.js");
const timelineIndex = html.indexOf("./timeline-core.js");
const recoveryIndex = html.indexOf("./project-recovery-core.js");
const storyboardIndex = html.indexOf("./storyboard-core.js");
const manualGuideIndex = html.indexOf("./manual-guide-core.js");
const poseIndex = html.indexOf("./pose-core.js");
const cameraDraftingIndex = html.indexOf("./camera-drafting-core.js");
const multiCameraIndex = html.indexOf("./multi-camera-core.js");
const appIndex = html.indexOf("./app.js");
assert.ok(motionIndex >= 0 && timelineIndex > motionIndex && recoveryIndex > timelineIndex && storyboardIndex > recoveryIndex && manualGuideIndex > storyboardIndex && poseIndex > manualGuideIndex && cameraDraftingIndex > poseIndex && multiCameraIndex > cameraDraftingIndex && appIndex > multiCameraIndex);
assert.ok(html.includes("./boot-errors.js"));
assert.ok(html.includes("./vendor/three.min.js"));
assert.ok(html.includes("./vendor/lucide.min.js"));
assert.equal(html.includes("cdn.jsdelivr.net"), false);
assert.equal(html.includes("unpkg.com"), false);

assert.ok(html.includes("class=\"manual-example\""), "manual needs a visual walkthrough example");
assert.ok(html.includes("class=\"manual-storage-map\""), "manual needs a project storage comparison");
assert.ok(html.includes("class=\"manual-camera-compare\""), "manual needs a framing comparison");
assert.ok(html.includes("class=\"manual-key-example\""), "manual needs a keyframe timing example");
assert.ok(html.includes("class=\"manual-preview-compare\""), "manual needs a preview workflow comparison");
assert.ok(ids.has("keyInstructionInput"), "timeline needs a per-key storyboard instruction field");
assert.match(app, /const \{\s*collisionEpsilon: timelineCollisionEpsilon,[\s\S]*?\} = timelineCore;/, "timeline collision helpers must come from the timeline core");
assert.ok(app.includes("const PROJECT_SCHEMA_VERSION = 11;"), "continuity and cut snapshots require project schema v11");
assert.ok(app.includes("function exportMultiCameraPreview("), "multi-camera preview needs a preview-first export action");
assert.ok(app.includes("function exportMultiCameraVideo("), "multi-camera needs a preview-first MP4 export action");
assert.ok(ids.has("multiCamVideoBtn") && ids.has("multiCamVideoPanelBtn"), "multi-camera video needs toolbar and panel actions");
assert.ok(app.includes("function exportSelectedCutFrame("), "selected cut needs a still-frame export action");
assert.ok(app.includes("function exportSelectedCutVideo("), "selected cut needs an MP4 export action");
assert.ok(app.includes("function selectCameraPreviewSlot("), "multi-camera preview slots need direct activation");
assert.ok(ids.has("cameraRigList") && ids.has("cameraFrameModeBtn"), "multi-camera controls need a rig list and preview mode control");
assert.ok(app.includes("function cameraFieldRenderEntries("), "2D and 3D fields must render every camera profile");
assert.ok(app.includes("cameraProfileId"), "3D camera rigs need a profile identity for selection");
assert.ok(app.includes('else if (initThreeView()) {') && app.includes("renderCameraFramePreview(renderState);"), "2D tab must render the shared camera preview");
assert.ok(app.includes("else renderCameraFramePreview(threeView.lastState || evaluatedViewState || state);"), "shared camera preview must resize in the 2D tab");
assert.ok(ids.has("cameraFrameResizeHandle"), "camera preview needs a shared resize handle");
assert.ok(ids.has("cameraFrameMoveHandle"), "camera preview needs a shared move handle");
assert.ok(app.includes("function setupCameraFrameResize(") && app.includes("function setCameraFrameWidth("), "camera preview resizing needs pointer and keyboard controls");
assert.ok(app.includes("function setCameraFramePosition(") && app.includes("function clampSavedCameraFramePosition("), "camera preview position needs bounded shared movement");
assert.ok(app.includes("--camera-frame-width"), "camera preview width must be applied through a shared layout value");
const threeWrapStart = html.indexOf('id="threeWrap"');
const cameraFrameStart = html.indexOf('id="cameraFrame"');
assert.ok(threeWrapStart >= 0 && cameraFrameStart > threeWrapStart, "camera preview must remain in the shared canvas wrapper");
assert.equal(html.slice(cameraFrameStart).includes('id="threeCanvas"'), false, "camera preview must not be nested inside the 3D viewport markup");
assert.equal(ids.has("cameraSensorFormat"), false, "advanced physical camera controls should stay out of the blocking sidebar");
assert.equal(ids.has("cameraSensorWidth"), false, "sensor width control should stay out of the blocking sidebar");
assert.equal(ids.has("cameraAperture"), false, "aperture control should stay out of the blocking sidebar");
assert.equal(ids.has("cameraFocusDistance"), false, "focus distance control should stay out of the blocking sidebar");
assert.ok(app.includes("focusDistanceM: lerp("), "camera focus distance must interpolate between keys");
assert.ok(html.includes('id="compareCutVersionsBtn"'), "storyboard inspector needs A/B cut comparison");
assert.ok(html.includes('id="cutVersionCompareDialog"'), "cut version comparison needs a dedicated dialog");
assert.ok(app.includes("function continuityFindings("), "structured continuity analysis adapter is required");
assert.ok(app.includes("function captureCutVersion("), "cut snapshot capture command is required");
assert.ok(ids.has("actorMotionFields") && ids.has("actorLocomotionMode"), "actors need a locomotion mode control");
assert.ok(app.includes("function actorLocomotionForSegment("), "actor movement needs procedural locomotion during interpolation");
assert.ok(html.includes('id="cutFocalInput" type="number" min="14" max="135"'), "storyboard lens input must preserve every supported focal length");
assert.ok(ids.has("actorPoseFields") && ids.has("actorPoseJointSelect") && ids.has("actorPoseKeyBtn"), "3D actors need pose controls and a pose key action");
assert.ok(html.includes('data-three-mode="pose"'), "3D toolbar needs a dedicated pose mode");
assert.ok(app.includes('model.name = "humanoid-rig-v2"'), "3D actors need the articulated mannequin rig");
assert.ok(/,\s*"nose"\);/.test(app), "3D actor face needs a nose mesh");
assert.ok(/,\s*"mouth"\);/.test(app), "3D actor face needs a mouth mesh");
assert.ok(app.includes("function captureActorPoseKeyframe("), "actor poses need timeline keyframe capture");
assert.ok(app.includes("function actorFocusHeight("), "camera tracking must include actor elevation and pitch");
assert.ok(app.includes('"vertical_offset", "pitch_deg"'), "CSV export must preserve actor elevation and pitch");
assert.ok(app.includes("function blenderCameraTarget("), "Blender export must use camera pan and tilt directly");
assert.ok(app.includes("obj.rotation_euler[0] = math.radians"), "Blender export must preserve actor pitch");
assert.ok(app.includes("function updateThreePoseDrag("), "3D actors need direct joint dragging");
assert.ok(app.includes("function updateExistingSourceKeyframe(sourceId, time"), "pose edits should update an existing key without creating an implicit one");
assert.equal(app.includes("function autoSaveDraggedPose(sourceId)"), false, "drag edits must not expose an implicit keyframe save path");
assert.equal(app.includes("const newKey = captureSourceKeyframe(sourceId, time, undefined, \"straight\");"), false, "drag edits must never create a new keyframe");
assert.ok(app.includes("function advancePlayheadAfterKeyframe("), "explicit key actions must advance the playhead");
assert.ok(app.includes("ensureDurationCovers(nextTime)"), "keyframe follow-up time must remain three seconds ahead at the timeline edge");
assert.ok(app.includes("function preserveLiveSourcePreview("), "unkeyed edits must remain visible until the user adds a key");
assert.ok(app.includes("function applyLiveSourceEdits("), "unkeyed edits must survive scrubbing until they are keyed");
assert.match(app, /function switchActiveCamera\(profileId\)[\s\S]*?syncActiveCameraProfile\(\);[\s\S]*?liveSourceEdits\.delete\("camera"\);/, "switching cameras must not transfer an unkeyed preview pose between rigs");
assert.doesNotMatch(app, /if \(hit\.kind === "camera"[\s\S]{0,220}switchActiveCamera\(hit\.profileId\);[\s\S]{0,220}return;/, "grabbing an inactive camera must select and drag it in one gesture");
assert.match(app, /\.sort\(\(a, b\) => a\.distance - b\.distance \|\| Number\(b\.entry\.active\) - Number\(a\.entry\.active\)\)/, "overlapping camera rigs must select the closest visible icon before the active rig");
assert.doesNotMatch(app, /autoSaveDraggedPose/, "scene dragging must never auto-update timeline keyframes");
assert.match(app, /const progress = transition === "smooth" \|\| transition === "linear" \? rawProgress : easedProgress;/, "continuous motion must not brake at ordinary keyframe boundaries");
assert.match(app, /routeAverageSpeed: movingDuration > 0 \? movingDistance \/ movingDuration : 0/, "actor locomotion mode must use one stable speed across the route");
assert.match(app, /const travelled = Math\.max\(0, Number\(timing\?\.routeDistanceBefore \|\| 0\)\) \+ distance \* clamp\(progress, 0, 1\);/, "walking and running cycles must continue across keyframe boundaries");
assert.match(app, /function rememberLiveSourceEdit\(sourceId\)[\s\S]*?liveSourceEdits\.set\(sourceId, \{ time, pose: currentPose \}\)/, "scene edits must remain independent even when a key exists at the playhead");
assert.ok(app.includes("function selectedPoseActor("), "pose actions must resolve an actor even after 3D selection changes");
assert.ok(app.includes("function applyActiveCameraTracking("), "camera tracking must survive keyed interpolation");
assert.ok(app.includes("applyActiveCameraTracking(next, state)"), "active camera tracking must be restored after state interpolation");
assert.ok(app.includes("const actor = current?.type === \"actor\""), "pose mode must select an actor before showing pose controls");
assert.ok(app.includes("function drawStoryboardNote("), "2D plan needs readable local instructions");
assert.ok(app.includes("function drawPlanPathArrows("), "2D plan needs repeated direction arrows");
assert.equal(app.includes("function drawBlockingGuideLegend("), false, "2D plan should not use a detached technical legend");
assert.equal(ids.has("cameraGuideCanvas"), false, "camera preview should not include a guide overlay canvas");
assert.equal(ids.has("cameraFrameMeta"), false, "camera preview should not include technical metadata");
assert.equal(ids.has("videoExportMode"), false, "video export should only create a clean preview");
assert.ok(ids.has("blockingPlanBtn") && ids.has("blockingPlanPanelBtn"), "2D blocking export needs toolbar and panel actions");
assert.ok(app.includes("function exportBlockingPlanImage("), "2D blocking export needs a preview-first renderer");
assert.ok(ids.has("productionPackBtn") && ids.has("productionPackPanelBtn"), "production data needs toolbar and panel actions");
assert.ok(app.includes('presentExport(zip, `${slug(project?.title || state.sceneTitle)}_production_pack.zip`'), "production data must use the preview-first export dialog");
assert.ok(app.includes('"project/cut_list.csv"') && app.includes('"docs/continuity_report.md"'), "production data must include cut and continuity reports");
assert.ok(app.includes('"project/multi_camera_plan.json"') && app.includes("function buildMultiCameraPlan("), "production data must include per-camera plans");
assert.ok(app.includes('"camera_id"'), "motion CSV must identify the camera that owns each camera key");
assert.ok(app.includes('"#productionPackBtn": "촬영 자료 ZIP"'), "production data must participate in the single-flight export lock");
assert.ok(app.includes('caption: "현재 컷 2D 동선도"') && app.includes('caption: "현재 재생 위치 카메라 프레임"'), "production preview must show actual rendered media");
assert.equal(app.includes("function downloadUrl("), false, "exports must not bypass the preview dialog");
assert.equal(app.includes("function downloadBlob("), false, "blob exports must not bypass the preview dialog");

assert.equal(html.includes("video-analysis-core.js"), false);
assert.equal(app.includes("referenceVideo"), false);
assert.equal(app.includes("referenceMedia"), false);
assert.equal([...app.matchAll(/\bfetch\(/g)].length, 1, "network requests must use fetchWithTimeout");

console.log("dom-contract: selectors, script order, retired UI, and request guard passed");
