#!/usr/bin/env python3
from pathlib import Path


def replace_once(text, old, new, label):
    if old not in text:
        raise SystemExit(f"missing patch anchor: {label}")
    if text.count(old) != 1:
        raise SystemExit(f"non-unique patch anchor: {label} ({text.count(old)})")
    return text.replace(old, new, 1)


motion_path = Path("motion-core.js")
motion = motion_path.read_text(encoding="utf-8")

helper_anchor = '''  function evaluateReferenceReadiness(blocking = {}, metadata = {}) {\n'''
helper_code = '''  function referenceTailDiscreteEvents(blocking = {}, exportRange = {}, fps = 24) {\n    const motion = blocking?.motion || {};\n    const duration = Math.max(0, finiteNumber(motion.duration, 0));\n    const rangeStart = clamp(finiteNumber(exportRange.start, 0), 0, duration);\n    const rangeEnd = clamp(finiteNumber(exportRange.end, duration), 0, duration);\n    if (!(rangeEnd > rangeStart)) return { lastSampleTime: rangeStart, events: [] };\n\n    const schedule = referenceExportFrameSchedule({ start: rangeStart, end: rangeEnd, fps });\n    const lastSampleTime = schedule.times.length ? schedule.times[schedule.times.length - 1] : rangeStart;\n    if (lastSampleTime >= rangeEnd - 0.0000005) return { lastSampleTime, events: [] };\n\n    const keyframes = [...(Array.isArray(motion.keyframes) ? motion.keyframes : [])]\n      .filter((keyframe) => Number.isFinite(Number(keyframe?.time)))\n      .sort((a, b) => Number(a.time) - Number(b.time));\n    const items = Array.isArray(blocking?.items) ? blocking.items : [];\n    const camera = blocking?.camera || {};\n    const events = [];\n\n    keyframes.forEach((keyframe, index) => {\n      const time = finiteNumber(keyframe?.time, -1);\n      if (time <= lastSampleTime + 0.0000005 || time > rangeEnd + 0.0000005 || time < rangeStart - 0.0000005) return;\n      const source = keyframe?.source || \"\";\n      const fallbackPose = source === \"camera\"\n        ? camera\n        : (items.find((item) => item?.id === source) || {});\n      let previousPose = { ...fallbackPose };\n      for (let previousIndex = index - 1; previousIndex >= 0; previousIndex -= 1) {\n        const candidate = keyframes[previousIndex];\n        if (candidate?.source !== source) continue;\n        if (finiteNumber(candidate?.time, time) >= time - 0.0000005) continue;\n        previousPose = { ...fallbackPose, ...(candidate?.pose || {}) };\n        break;\n      }\n      const currentPose = { ...fallbackPose, ...(keyframe?.pose || {}) };\n      const reasons = [];\n      const transition = normalizeTransition(keyframe?.transition);\n      if (transition === \"hold\" || transition === \"cut\") reasons.push(transition);\n      if (source === \"camera\") {\n        if (String(previousPose.trackingTargetId || \"\") !== String(currentPose.trackingTargetId || \"\")) {\n          reasons.push(\"tracking\");\n        }\n      } else if (fallbackPose?.type === \"actor\") {\n        const previousBodyPose = JSON.stringify(previousPose.bodyPose ?? null);\n        const currentBodyPose = JSON.stringify(currentPose.bodyPose ?? null);\n        if (previousBodyPose !== currentBodyPose) reasons.push(\"actor-pose\");\n      }\n      if (!reasons.length) return;\n      events.push({\n        id: keyframe?.id || \"\",\n        source,\n        time,\n        reasons,\n      });\n    });\n\n    return { lastSampleTime, events };\n  }\n\n'''
motion = replace_once(motion, helper_anchor, helper_code + helper_anchor, "readiness helper insertion")

readiness_anchor = '''    if (invalidPoseCount) addReadinessIssue(issues, \"error\", \"key-pose-invalid\", `숫자 값이 깨진 키가 ${invalidPoseCount}개 있습니다.`);\n    if (offFrameGrid) addReadinessIssue(issues, \"warning\", \"keys-off-frame-grid\", `${offFrameGrid}개 키가 ${Math.round(fps)}FPS 프레임 틱에서 벗어나 있습니다.`);\n\n    const errorCount = issues.filter((issue) => issue.severity === \"error\").length;\n'''
readiness_replacement = '''    if (invalidPoseCount) addReadinessIssue(issues, \"error\", \"key-pose-invalid\", `숫자 값이 깨진 키가 ${invalidPoseCount}개 있습니다.`);\n    if (offFrameGrid) addReadinessIssue(issues, \"warning\", \"keys-off-frame-grid\", `${offFrameGrid}개 키가 ${Math.round(fps)}FPS 프레임 틱에서 벗어나 있습니다.`);\n\n    let tailDiscrete = { lastSampleTime: rangeStart, events: [] };\n    const validRangeForSampling = rangeStart >= 0\n      && rangeEnd <= duration + 0.0005\n      && rangeEnd > rangeStart;\n    const validFpsForSampling = Number.isFinite(Number(fps)) && fps >= 12 && fps <= 60;\n    if (validRangeForSampling && validFpsForSampling) {\n      tailDiscrete = referenceTailDiscreteEvents(blocking, { start: rangeStart, end: rangeEnd }, fps);\n      if (tailDiscrete.events.length) {\n        addReadinessIssue(\n          issues,\n          \"warning\",\n          \"tail-discrete-event-unsampled\",\n          `${tailDiscrete.events.length}개 도착 전환이 마지막 CFR 샘플(${tailDiscrete.lastSampleTime.toFixed(3)}초) 뒤에 있어 MP4에 직접 나타나지 않습니다. 키를 최소 1프레임 앞당기거나 출력 구간을 늘리세요.`,\n        );\n      }\n    }\n\n    const errorCount = issues.filter((issue) => issue.severity === \"error\").length;\n'''
motion = replace_once(motion, readiness_anchor, readiness_replacement, "readiness warning insertion")

stats_anchor = '''        cameraKeyCount: keyframes.filter((keyframe) => keyframe.source === \"camera\").length,\n'''
stats_replacement = '''        cameraKeyCount: keyframes.filter((keyframe) => keyframe.source === \"camera\").length,\n        tailDiscreteEventCount: tailDiscrete.events.length,\n'''
motion = replace_once(motion, stats_anchor, stats_replacement, "readiness stats")

export_anchor = '''    referenceEntryKey,\n    referenceExportFrameSchedule,\n'''
export_replacement = '''    referenceEntryKey,\n    referenceExportFrameSchedule,\n    referenceTailDiscreteEvents,\n'''
motion = replace_once(motion, export_anchor, export_replacement, "motion-core export")

motion_path.write_text(motion, encoding="utf-8")


test_path = Path("tests/reference-readiness.test.cjs")
test = test_path.read_text(encoding="utf-8")

import_anchor = '''  isFrameAligned,\n} = motion;\n'''
import_replacement = '''  isFrameAligned,\n  referenceTailDiscreteEvents,\n} = motion;\n'''
test = replace_once(test, import_anchor, import_replacement, "test import")

test_anchor = '''const invalidRange = baseBlocking();\ninvalidRange.motion.exportRange = { start: 4, end: 2 };\nconst invalidRangeResult = evaluateReferenceReadiness(invalidRange);\nassert.equal(invalidRangeResult.status, \"blocked\");\nassert.ok(invalidRangeResult.issues.some((issue) => issue.code === \"export-range-invalid\"));\n\nconst projectResults = evaluateProjectReferenceReadiness({\n'''
test_replacement = '''const invalidRange = baseBlocking();\ninvalidRange.motion.exportRange = { start: 4, end: 2 };\nconst invalidRangeResult = evaluateReferenceReadiness(invalidRange);\nassert.equal(invalidRangeResult.status, \"blocked\");\nassert.ok(invalidRangeResult.issues.some((issue) => issue.code === \"export-range-invalid\"));\n\nconst smoothEnd = baseBlocking();\nsmoothEnd.motion.keyframes.push({\n  id: \"cam-end-smooth\",\n  source: \"camera\",\n  time: 5,\n  transition: \"smooth\",\n  pose: { x: 0.6, y: 0.5, height: 1.6, panDeg: 180, tiltDeg: -4, focal: 50, trackingTargetId: \"actor-1\" },\n});\nconst smoothEndResult = evaluateReferenceReadiness(smoothEnd);\nassert.equal(smoothEndResult.status, \"ready\", \"ordinary smooth endpoint keys must not become false-positive reviews\");\nassert.equal(smoothEndResult.stats.tailDiscreteEventCount, 0);\n\nconst holdEnd = baseBlocking();\nholdEnd.motion.keyframes.push({\n  id: \"actor-end-hold\",\n  source: \"actor-1\",\n  time: 5,\n  transition: \"hold\",\n  pose: { x: 0.6, y: 0.5, facing: 0 },\n});\nconst holdEndResult = evaluateReferenceReadiness(holdEnd);\nassert.equal(holdEndResult.status, \"review\");\nassert.ok(holdEndResult.issues.some((issue) => issue.code === \"tail-discrete-event-unsampled\"));\nassert.equal(holdEndResult.stats.tailDiscreteEventCount, 1);\n\nconst poseEnd = baseBlocking();\nposeEnd.items[0].bodyPose = { leftArm: { x: 0 } };\nposeEnd.motion.keyframes[2].pose.bodyPose = { leftArm: { x: 0 } };\nposeEnd.motion.keyframes.push({\n  id: \"actor-end-pose\",\n  source: \"actor-1\",\n  time: 5,\n  transition: \"smooth\",\n  pose: { x: 0.55, y: 0.5, facing: 0, bodyPose: { leftArm: { x: -40 } } },\n});\nconst poseEndResult = evaluateReferenceReadiness(poseEnd);\nassert.equal(poseEndResult.status, \"review\");\nassert.ok(poseEndResult.issues.some((issue) => issue.code === \"tail-discrete-event-unsampled\"));\n\nconst trackingEnd = baseBlocking();\ntrackingEnd.items.push({ id: \"actor-2\", type: \"actor\", name: \"B\", x: 0.6, y: 0.5, facing: 180 });\ntrackingEnd.motion.keyframes.push({\n  id: \"cam-end-tracking\",\n  source: \"camera\",\n  time: 5,\n  transition: \"smooth\",\n  pose: { x: 0.7, y: 0.5, height: 1.6, panDeg: 180, tiltDeg: -4, focal: 50, trackingTargetId: \"actor-2\" },\n});\nconst trackingEndResult = evaluateReferenceReadiness(trackingEnd);\nassert.equal(trackingEndResult.status, \"review\");\nassert.ok(trackingEndResult.issues.some((issue) => issue.code === \"tail-discrete-event-unsampled\"));\n\nconst tailPlan = referenceTailDiscreteEvents(trackingEnd, { start: 0, end: 5 }, 24);\nassert.ok(Math.abs(tailPlan.lastSampleTime - 119 / 24) < 0.000001);\nassert.equal(tailPlan.events.length, 1);\nassert.ok(tailPlan.events[0].reasons.includes(\"tracking\"));\n\nconst projectResults = evaluateProjectReferenceReadiness({\n'''
test = replace_once(test, test_anchor, test_replacement, "tail readiness tests")

test_path.write_text(test, encoding="utf-8")
print("reference tail discrete readiness patch applied")
