from pathlib import Path

core_path = Path('reference-workflow-core.js')
core = core_path.read_text(encoding='utf-8')

old = '''  function normalizeReferencePromptPlatform(value) {\n    const normalized = String(value || "seedance").trim().toLowerCase();\n    return ["seedance", "higgsfield", "runway", "prompt-writer"].includes(normalized) ? normalized : "seedance";\n  }\n\n  function referencePromptPlatformNote(platform = "seedance") {\n    const normalized = normalizeReferencePromptPlatform(platform);\n    if (normalized === "higgsfield") return "Higgsfield는 생성 플랫폼입니다. 이 템플릿은 튜토리얼과 가장 가까운 Higgsfield + Seedance Video-to-Video 조합을 기준으로 합니다.";\n    if (normalized === "runway") return "Runway는 모델별 레퍼런스 동작이 다릅니다. 이 템플릿은 Aleph/Edit Studio 계열처럼 입력 영상을 보존·변환하는 흐름을 기준으로 짧고 직접적인 지시를 사용합니다.";\n    if (normalized === "prompt-writer") return "튜토리얼처럼 Claude/Fable 같은 외부 도구에 FrisFrame MP4와 이미지 레퍼런스를 첨부하고, 초 단위 Seedance 프롬프트를 작성하게 하는 요청문입니다.";\n    return "Seedance Video-to-Video 기준입니다. FrisFrame MP4는 카메라·블로킹·타이밍을, 이미지/텍스트 레퍼런스는 인물·장소·스타일을 담당하도록 역할을 분리합니다.";\n  }\n\n'''
new = '''  function normalizeReferencePromptPlatform(value) {\n    const normalized = String(value || "generic").trim().toLowerCase();\n    return ["generic", "higgsfield", "runway"].includes(normalized) ? normalized : "generic";\n  }\n\n  function normalizeReferencePromptModel(value) {\n    const normalized = String(value || "seedance-2.5").trim().toLowerCase();\n    return ["seedance-2.5", "seedance-2.0", "aleph-2.0", "generic"].includes(normalized) ? normalized : "seedance-2.5";\n  }\n\n  function normalizeReferencePromptOutput(value) {\n    const normalized = String(value || "final").trim().toLowerCase();\n    return ["final", "prompt-writer"].includes(normalized) ? normalized : "final";\n  }\n\n  function referencePromptPlatformNote(platform = "generic") {\n    const normalized = normalizeReferencePromptPlatform(platform);\n    if (normalized === "higgsfield") return "Higgsfield는 여러 생성 모델을 선택해 사용하는 제작 플랫폼입니다. 아래 모델 선택과는 별개입니다.";\n    if (normalized === "runway") return "Runway는 여러 생성/편집 모델을 사용하는 제작 플랫폼입니다. Seedance 2.5 같은 외부 모델과 Aleph 2.0 같은 Runway 모델을 구분해 선택합니다.";\n    return "직접 API·다른 제작 플랫폼·모델 제공사 UI에서 사용할 때 선택합니다. 플랫폼과 생성 모델은 서로 다른 개념입니다.";\n  }\n\n  function referencePromptModelNote(model = "seedance-2.5") {\n    const normalized = normalizeReferencePromptModel(model);\n    if (normalized === "seedance-2.5") return "Seedance 2.5는 ByteDance의 비디오 생성 모델입니다. 텍스트·이미지·비디오·오디오 레퍼런스를 역할별로 사용할 수 있습니다.";\n    if (normalized === "seedance-2.0") return "Seedance 2.0은 ByteDance의 멀티모달 비디오 생성 모델입니다. 플랫폼과 무관하게 레퍼런스 역할을 명확히 지정하는 템플릿을 사용합니다.";\n    if (normalized === "aleph-2.0") return "Aleph 2.0은 Runway의 비디오 편집 모델입니다. 기존 영상의 구조를 유지하면서 무엇을 바꿀지 짧고 직접적으로 지시하는 방식이 적합합니다.";\n    return "기타 레퍼런스 지원 모델용 일반 템플릿입니다. 실제 입력 규칙은 선택한 모델 문서를 확인하세요.";\n  }\n\n'''
if old not in core:
    raise SystemExit('platform taxonomy marker not found')
core = core.replace(old, new, 1)

old = '''  function buildReferencePromptGuide(entry = {}, platform = "seedance", options = {}) {\n    const normalized = normalizeReferencePromptPlatform(platform);\n    const referenceRole = normalizeReferencePromptRole(options.referenceRole);\n'''
new = '''  function buildReferencePromptGuide(entry = {}, platform = "generic", options = {}) {\n    const normalized = normalizeReferencePromptPlatform(platform);\n    const model = normalizeReferencePromptModel(options.model);\n    const outputMode = normalizeReferencePromptOutput(options.outputMode);\n    const referenceRole = normalizeReferencePromptRole(options.referenceRole);\n'''
if old not in core:
    raise SystemExit('build function marker not found')
core = core.replace(old, new, 1)

old = '''    if (normalized === "prompt-writer") {\n      return [\n        `Write a ${duration.toFixed(2)}-second Seedance video-to-video prompt based on the attached FrisFrame blocking MP4.`,\n        `The shot is ${cutLabel} at ${fps} FPS. Read the entire input video and write the final generation prompt second-by-second so it matches the authored camera path, framing, lens changes, actor root blocking, spatial relationships, and timing.`,\n        roleInstruction,\n        "Treat character/location/creative references as appearance references: identity, wardrobe, environment, color palette, lighting, materials, and mood. Keep natural secondary body motion subtle and compatible with the authored blocking instead of inventing a different camera or root path.",\n        "Return the prompt in these sections: SHOT, ACTIVE REFERENCES, GLOBAL STYLE, SCENE / ACTION, SECOND-BY-SECOND TIMELINE, AUDIO / SFX.",\n        "",\n        `SCENE / ACTION NOTES: ${story}`,\n        `REFERENCE MAP: ${references}`,\n        `VISUAL TARGET: ${style}`,\n        `AUDIO / SFX: ${audio}`,\n      ].join("\\n");\n    }\n\n    if (normalized === "runway") {\n      return [\n        `RUNWAY REFERENCE STARTER · ${cutLabel} · ${duration.toFixed(2)}s`,\n        "",\n        referenceRole === "motion"\n          ? "Transform the FrisFrame motion reference into the requested final scene while preserving its motion sequence, speed, timing, actor root path, explicit pose changes, and encoded camera motion."\n          : "Transform the FrisFrame previs into the requested final scene while preserving the input video's spatial layout, camera trajectory, timing, framing, subject position/blocking, and spatial relationships.",\n        `Scene/action: ${story}`,\n        `Replace placeholder geometry with these final references/subjects: ${references}`,\n        `Final visual target: ${style}`,\n        `Motion/audio notes: ${audio}`,\n        "Keep the requested transformation specific and concise. Add extra motion only when it supports the authored blocking.",\n        "",\n        "Reference usage: @Video 1 = FrisFrame previs structure. Add image/video references with Runway's @ reference picker when the selected model supports them.",\n      ].join("\\n");\n    }\n\n    const heading = normalized === "higgsfield"\n      ? "HIGGSFIELD · SEEDANCE VIDEO-TO-VIDEO"\n      : "SEEDANCE VIDEO-TO-VIDEO";\n'''
new = '''    const platformLabel = normalized === "higgsfield" ? "HIGGSFIELD" : normalized === "runway" ? "RUNWAY" : "DIRECT / OTHER PLATFORM";\n    const modelLabel = model === "seedance-2.5" ? "SEEDANCE 2.5" : model === "seedance-2.0" ? "SEEDANCE 2.0" : model === "aleph-2.0" ? "ALEPH 2.0" : "GENERIC REFERENCE MODEL";\n\n    if (outputMode === "prompt-writer") {\n      const targetInstruction = model === "aleph-2.0"\n        ? `Write a concise Runway Aleph 2.0 transformation prompt for the attached ${duration.toFixed(2)}-second FrisFrame MP4.`\n        : model.startsWith("seedance-")\n          ? `Write a ${duration.toFixed(2)}-second ${modelLabel} reference-video prompt based on the attached FrisFrame MP4.`\n          : `Write a ${duration.toFixed(2)}-second reference-video generation prompt for the selected model based on the attached FrisFrame MP4.`;\n      return [\n        `PLATFORM: ${platformLabel}`,\n        `MODEL: ${modelLabel}`,\n        targetInstruction,\n        `The shot is ${cutLabel} at ${fps} FPS. Read the entire input video before writing the prompt.`,\n        roleInstruction,\n        "Treat character/location/creative references as appearance references: identity, wardrobe, environment, color palette, lighting, materials, and mood.",\n        model === "aleph-2.0"\n          ? "For Aleph 2.0, keep the final transformation prompt short, precise, and limited to what should change while preserving the source structure."\n          : "For Seedance/reference generation, describe scene meaning and reference roles without re-inventing camera/root motion already encoded in the FrisFrame MP4.",\n        "",\n        `SCENE / ACTION NOTES: ${story}`,\n        `REFERENCE MAP: ${references}`,\n        `VISUAL TARGET: ${style}`,\n        `AUDIO / SFX: ${audio}`,\n      ].join("\\n");\n    }\n\n    if (model === "aleph-2.0") {\n      return [\n        `${platformLabel} · ALEPH 2.0 · ${cutLabel} · ${duration.toFixed(2)}s`,\n        "",\n        referenceRole === "motion"\n          ? "Transform the FrisFrame motion reference into the requested final scene while preserving its motion sequence, speed, timing, actor root path, explicit pose changes, and encoded camera motion."\n          : "Transform the FrisFrame previs into the requested final scene while preserving the input video's spatial layout, camera trajectory, timing, framing, subject position/blocking, and spatial relationships.",\n        `Change/replace: ${story}`,\n        `Use these appearance references: ${references}`,\n        `Final visual target: ${style}`,\n        `Audio notes: ${audio}`,\n        "Keep the instruction concise and change only what is requested. Preserve the rest of the source structure.",\n      ].join("\\n");\n    }\n\n    const heading = `${platformLabel} · ${modelLabel}`;\n'''
if old not in core:
    raise SystemExit('template taxonomy marker not found')
core = core.replace(old, new, 1)

old = '''    const platformSelect = documentObject.createElement("select");\n    Object.assign(platformSelect.style, fieldStyle);\n    [\n      ["seedance", "Seedance V2V"],\n      ["higgsfield", "Higgsfield · Seedance V2V"],\n      ["runway", "Runway · Reference / Aleph"],\n      ["prompt-writer", "Claude / Fable · 프롬프트 작성 요청"],\n    ].forEach(([value, label]) => {\n      const option = documentObject.createElement("option");\n      option.value = value;\n      option.textContent = label;\n      platformSelect.appendChild(option);\n    });\n    const platformNote = documentObject.createElement("div");\n    Object.assign(platformNote.style, { color: "#91a69a", fontSize: "11px", lineHeight: "1.45" });\n'''
new = '''    const platformSelect = documentObject.createElement("select");\n    Object.assign(platformSelect.style, fieldStyle);\n    [\n      ["generic", "직접 / 기타 플랫폼"],\n      ["higgsfield", "Higgsfield"],\n      ["runway", "Runway"],\n    ].forEach(([value, label]) => {\n      const option = documentObject.createElement("option");\n      option.value = value;\n      option.textContent = label;\n      platformSelect.appendChild(option);\n    });\n    const platformNote = documentObject.createElement("div");\n    Object.assign(platformNote.style, { color: "#91a69a", fontSize: "11px", lineHeight: "1.45" });\n    const modelSelect = documentObject.createElement("select");\n    Object.assign(modelSelect.style, fieldStyle);\n    [\n      ["seedance-2.5", "Seedance 2.5 · ByteDance"],\n      ["seedance-2.0", "Seedance 2.0 · ByteDance"],\n      ["aleph-2.0", "Aleph 2.0 · Runway"],\n      ["generic", "기타 Reference 지원 모델"],\n    ].forEach(([value, label]) => {\n      const option = documentObject.createElement("option");\n      option.value = value;\n      option.textContent = label;\n      modelSelect.appendChild(option);\n    });\n    const modelNote = documentObject.createElement("div");\n    Object.assign(modelNote.style, { color: "#91a69a", fontSize: "11px", lineHeight: "1.45" });\n    const outputModeSelect = documentObject.createElement("select");\n    Object.assign(outputModeSelect.style, fieldStyle);\n    [\n      ["final", "최종 생성 프롬프트"],\n      ["prompt-writer", "Claude / Fable 등에 프롬프트 작성 요청"],\n    ].forEach(([value, label]) => {\n      const option = documentObject.createElement("option");\n      option.value = value;\n      option.textContent = label;\n      outputModeSelect.appendChild(option);\n    });\n'''
if old not in core:
    raise SystemExit('platform UI marker not found')
core = core.replace(old, new, 1)

old = '''      makeLabel("대상", platformSelect),\n      platformNote,\n      makeLabel("FrisFrame MP4 역할", roleSelect),\n'''
new = '''      makeLabel("사용 플랫폼", platformSelect),\n      platformNote,\n      makeLabel("생성 / 편집 모델", modelSelect),\n      modelNote,\n      makeLabel("출력 방식", outputModeSelect),\n      makeLabel("FrisFrame MP4 역할", roleSelect),\n'''
if old not in core:
    raise SystemExit('UI append marker not found')
core = core.replace(old, new, 1)

old = '''      platformNote.textContent = referencePromptPlatformNote(platformSelect.value);\n      roleNote.textContent = referencePromptRoleNote(roleSelect.value);\n      const entry = selectedEntry();\n      output.value = entry ? buildReferencePromptGuide(entry, platformSelect.value, {\n        referenceRole: roleSelect.value,\n'''
new = '''      platformNote.textContent = referencePromptPlatformNote(platformSelect.value);\n      modelNote.textContent = referencePromptModelNote(modelSelect.value);\n      roleNote.textContent = referencePromptRoleNote(roleSelect.value);\n      const entry = selectedEntry();\n      output.value = entry ? buildReferencePromptGuide(entry, platformSelect.value, {\n        model: modelSelect.value,\n        outputMode: outputModeSelect.value,\n        referenceRole: roleSelect.value,\n'''
if old not in core:
    raise SystemExit('refresh taxonomy marker not found')
core = core.replace(old, new, 1)

old = '''    platformSelect.addEventListener("change", refreshOutput);\n    roleSelect.addEventListener("change", refreshOutput);\n'''
new = '''    platformSelect.addEventListener("change", refreshOutput);\n    modelSelect.addEventListener("change", refreshOutput);\n    outputModeSelect.addEventListener("change", refreshOutput);\n    roleSelect.addEventListener("change", refreshOutput);\n'''
if old not in core:
    raise SystemExit('listeners taxonomy marker not found')
core = core.replace(old, new, 1)

old = '''    normalizeReferencePromptPlatform,\n    normalizeReferencePromptRole,\n    partitionReferenceBatchByReadiness,\n    referencePromptPlatformNote,\n    referencePromptRoleNote,\n'''
new = '''    normalizeReferencePromptModel,\n    normalizeReferencePromptOutput,\n    normalizeReferencePromptPlatform,\n    normalizeReferencePromptRole,\n    partitionReferenceBatchByReadiness,\n    referencePromptModelNote,\n    referencePromptPlatformNote,\n    referencePromptRoleNote,\n'''
if old not in core:
    raise SystemExit('exports taxonomy marker not found')
core = core.replace(old, new, 1)

core_path.write_text(core, encoding='utf-8')

# Update regression tests.
test_path = Path('tests/reference-prompt-guide.test.cjs')
test = test_path.read_text(encoding='utf-8')
test = test.replace('''  normalizeReferencePromptPlatform,\n  normalizeReferencePromptRole,\n  referencePromptPlatformNote,\n  referencePromptRoleNote,\n''', '''  normalizeReferencePromptModel,\n  normalizeReferencePromptOutput,\n  normalizeReferencePromptPlatform,\n  normalizeReferencePromptRole,\n  referencePromptModelNote,\n  referencePromptPlatformNote,\n  referencePromptRoleNote,\n''')
test = test.replace('''assert.equal(normalizeReferencePromptPlatform("RUNWAY"), "runway");\nassert.equal(normalizeReferencePromptPlatform("unknown"), "seedance");\nassert.ok(referencePromptPlatformNote("higgsfield").includes("플랫폼"));\nassert.ok(referencePromptPlatformNote("runway").includes("모델별"));\n''', '''assert.equal(normalizeReferencePromptPlatform("RUNWAY"), "runway");\nassert.equal(normalizeReferencePromptPlatform("unknown"), "generic");\nassert.equal(normalizeReferencePromptModel("SEEDANCE-2.5"), "seedance-2.5");\nassert.equal(normalizeReferencePromptModel("unknown"), "seedance-2.5");\nassert.equal(normalizeReferencePromptOutput("PROMPT-WRITER"), "prompt-writer");\nassert.ok(referencePromptPlatformNote("higgsfield").includes("플랫폼"));\nassert.ok(referencePromptPlatformNote("runway").includes("Seedance 2.5"));\nassert.ok(referencePromptModelNote("seedance-2.5").includes("ByteDance"));\nassert.ok(referencePromptModelNote("aleph-2.0").includes("Runway"));\n''')
test = test.replace('''const seedance = buildReferencePromptGuide(entry, "seedance", { ...options, referenceRole: "previs" });\n''', '''const seedance = buildReferencePromptGuide(entry, "higgsfield", { ...options, model: "seedance-2.5", outputMode: "final", referenceRole: "previs" });\n''')
test = test.replace('''assert.ok(seedance.includes("SEEDANCE VIDEO-TO-VIDEO"));\n''', '''assert.ok(seedance.includes("HIGGSFIELD · SEEDANCE 2.5"));\n''')
test = test.replace('''const higgsfield = buildReferencePromptGuide(entry, "higgsfield", { ...options, referenceRole: "motion" });\nassert.ok(higgsfield.includes("HIGGSFIELD · SEEDANCE VIDEO-TO-VIDEO"));\nassert.ok(higgsfield.includes("@video_1"));\nassert.ok(higgsfield.includes("FrisFrame motion reference MP4"));\nassert.ok(higgsfield.includes("motion sequence, speed, timing"));\n\nconst runway = buildReferencePromptGuide(entry, "runway", { ...options, referenceRole: "motion" });\nassert.ok(runway.includes("RUNWAY REFERENCE STARTER"));\nassert.ok(runway.includes("preserving its motion sequence"));\nassert.ok(runway.includes("@Video 1"));\n\nconst writer = buildReferencePromptGuide(entry, "prompt-writer", options);\nassert.ok(writer.includes("Write a 12.00-second Seedance video-to-video prompt"));\nassert.ok(writer.includes("second-by-second"));\nassert.ok(writer.includes("attached FrisFrame blocking MP4"));\nassert.ok(writer.includes("SECOND-BY-SECOND TIMELINE"));\n''', '''const runwaySeedance = buildReferencePromptGuide(entry, "runway", { ...options, model: "seedance-2.5", referenceRole: "motion" });\nassert.ok(runwaySeedance.includes("RUNWAY · SEEDANCE 2.5"));\nassert.ok(runwaySeedance.includes("FrisFrame motion reference MP4"));\n\nconst aleph = buildReferencePromptGuide(entry, "runway", { ...options, model: "aleph-2.0", referenceRole: "motion" });\nassert.ok(aleph.includes("RUNWAY · ALEPH 2.0"));\nassert.ok(aleph.includes("preserving its motion sequence"));\n\nconst writer = buildReferencePromptGuide(entry, "higgsfield", { ...options, model: "seedance-2.5", outputMode: "prompt-writer", referenceRole: "previs" });\nassert.ok(writer.includes("PLATFORM: HIGGSFIELD"));\nassert.ok(writer.includes("MODEL: SEEDANCE 2.5"));\nassert.ok(writer.includes("Write a 12.00-second SEEDANCE 2.5 reference-video prompt"));\n''')
test = test.replace('''assert.ok(source.includes('"3D 프리비즈 · 공간/카메라"'));\n''', '''assert.ok(source.includes('"Higgsfield"'));\nassert.ok(source.includes('"Runway"'));\nassert.ok(source.includes('"Seedance 2.5 · ByteDance"'));\nassert.ok(source.includes('"Aleph 2.0 · Runway"'));\nassert.ok(source.includes('"3D 프리비즈 · 공간/카메라"'));\n''')
test_path.write_text(test, encoding='utf-8')

# Correct the guide taxonomy explicitly.
guide_path = Path('REFERENCE_PROMPT_GUIDE.md')
guide = guide_path.read_text(encoding='utf-8')
correction = '''\n## 플랫폼과 모델은 반드시 구분한다\n\nFrisFrame의 프롬프트 가이드에서는 다음 네 가지를 서로 다른 층으로 취급합니다.\n\n```text\n사용 플랫폼\n→ Higgsfield / Runway / 직접·기타\n\n생성·편집 모델\n→ Seedance 2.5 / Seedance 2.0 / Aleph 2.0 / 기타\n\n출력 방식\n→ 최종 생성 프롬프트 / Claude·Fable 등에 프롬프트 작성 요청\n\nFrisFrame MP4 역할\n→ 3D 프리비즈(공간·카메라) / 모션 레퍼런스(동작·타이밍)\n```\n\n**Higgsfield와 Runway는 플랫폼**입니다. 그 안에서 여러 모델을 선택할 수 있습니다. **Seedance는 ByteDance의 비디오 생성 모델군**이며 Higgsfield와 Runway 같은 플랫폼에서 제공될 수 있습니다. **Aleph 2.0은 Runway의 비디오 편집 모델**입니다.\n\n따라서 `Higgsfield = Seedance` 또는 `Runway = Aleph`처럼 동일시하지 않습니다. 예를 들어 `Runway → Seedance 2.5 → 3D 프리비즈`도 가능하고, `Runway → Aleph 2.0 → 모션 레퍼런스`처럼 사용할 수도 있습니다.\n\n'''
marker = '## 첨부 튜토리얼에서 확인한 핵심\n'
if '## 플랫폼과 모델은 반드시 구분한다' not in guide:
    if marker not in guide:
        raise SystemExit('guide taxonomy marker not found')
    guide = guide.replace(marker, correction + marker, 1)
guide_path.write_text(guide, encoding='utf-8')
